
package org.wso2.carbon.event.execution.manager.admin;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExecutionManagerAdminService", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org", 
wsdlLocation = "file:/C:/Users/pcseg369/Desktop/ExecutionManagerAdminService.xml")
public class ExecutionManagerAdminService
extends Service
{

	private final static URL EXECUTIONMANAGERADMINSERVICE_WSDL_LOCATION;
	private final static WebServiceException EXECUTIONMANAGERADMINSERVICE_EXCEPTION;
	private final static QName EXECUTIONMANAGERADMINSERVICE_QNAME = new QName("http://admin.manager.execution.event.carbon.wso2.org", "ExecutionManagerAdminService");

	static {
		URL url = null;
		WebServiceException e = null;
		try {
			url = new URL("file:/C:/Users/pcseg369/Desktop/ExecutionManagerAdminService.xml");
		} catch (MalformedURLException ex) {
			e = new WebServiceException(ex);
		}
		EXECUTIONMANAGERADMINSERVICE_WSDL_LOCATION = url;
		EXECUTIONMANAGERADMINSERVICE_EXCEPTION = e;
	}

	public ExecutionManagerAdminService() {
		super(__getWsdlLocation(), EXECUTIONMANAGERADMINSERVICE_QNAME);
	}

	public ExecutionManagerAdminService(WebServiceFeature... features) {
		super(__getWsdlLocation(), EXECUTIONMANAGERADMINSERVICE_QNAME, features);
	}

	public ExecutionManagerAdminService(URL wsdlLocation) {
		super(wsdlLocation, EXECUTIONMANAGERADMINSERVICE_QNAME);
	}

	public ExecutionManagerAdminService(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, EXECUTIONMANAGERADMINSERVICE_QNAME, features);
	}

	public ExecutionManagerAdminService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ExecutionManagerAdminService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * 
	 * @return
	 *     returns ExecutionManagerAdminServicePortType
	 */
	@WebEndpoint(name = "ExecutionManagerAdminServiceHttpsSoap11Endpoint")
	public ExecutionManagerAdminServicePortType getExecutionManagerAdminServiceHttpsSoap11Endpoint() {
		return super.getPort(new QName("http://admin.manager.execution.event.carbon.wso2.org", "ExecutionManagerAdminServiceHttpsSoap11Endpoint"), ExecutionManagerAdminServicePortType.class);
	}

	/**
	 * 
	 * @param features
	 *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
	 * @return
	 *     returns ExecutionManagerAdminServicePortType
	 */
	@WebEndpoint(name = "ExecutionManagerAdminServiceHttpsSoap11Endpoint")
	public ExecutionManagerAdminServicePortType getExecutionManagerAdminServiceHttpsSoap11Endpoint(WebServiceFeature... features) {
		return super.getPort(new QName("http://admin.manager.execution.event.carbon.wso2.org", "ExecutionManagerAdminServiceHttpsSoap11Endpoint"), ExecutionManagerAdminServicePortType.class, features);
	}

	private static URL __getWsdlLocation() {
		if (EXECUTIONMANAGERADMINSERVICE_EXCEPTION!= null) {
			throw EXECUTIONMANAGERADMINSERVICE_EXCEPTION;
		}
		return EXECUTIONMANAGERADMINSERVICE_WSDL_LOCATION;
	}

}
