   registryHost : 10.236.166.131
   registryPort : 1099   
   registryName : distributor
   host : 10.236.166.113
   port : 9763
   scheme : http
   getAllActiveDeviceApi : /datasource-api-1.0.0/services/datasources/device_activity/active
   getAllDeviceApi : /datasource-api-1.0.0/services/datasources/devices/findall
   persistTransitionApi : /datasource-api-1.0.0/services/datasources/device_activity/transition