apiMgrClientId : vZlfm2cKuHuMLJhJSd32mleFP3ga
apiMgrClientSecret : jRFf9e4AAiyHAwGaIRLjtIkOvq8a
gxyApiMgrClientId : YI0HGCpkjDtaNi37aCwVlSeI0uYa
gxyApiMgrClientSecret : YXizr8nu8TZlmfsrcPfV7LPkX5Ya
host : 10.236.166.115
port : 8282
scheme : http
getAssetsApi : markers/1.0.0/markers/fieldvalue/search
getLatestDataApi : saffron/1.0.0/data/{source_id}/latest
getCcdAssetsApi : ccd/1.0.0/equipment/findall
getAllCcdTenantsApi : ccd/1.0.0/tenants/findall
ccdUser : ccdadmin@ccd.galaxy
ccdUserPwd : password
gxyUser : ccdadmin@pcs.galaxy
gxyUserPwd : password