package com.pcs.alpine.constants;

/**
 * @description Responsible for holding the constants related to Swagger Api
 *              documentation
 * @author Twinkle (PCSEG297)
 * @date Oct 2015
 * @since galaxy-1.0.0
 */
public interface ApiDocConstant {

	public final static String ATTACH_CHILDREN_DESC = "This service is used to attach mulitple child entities to a parent entity, sample request : "
	        + "{\"actor\":{\"domain\":{\"domainName\":\"alpine.com\"},\"entityTemplate\":{\"entityTemplateName\":\"DefaultTenant\"},\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"identifier\":{\"key\":\"tenantName\",\"value\":\"Chocos05\"}},\"subjects\":[{\"domain\":{\"domainName\":\"alpine.com\"},\"entityTemplate\":{\"entityTemplateName\":\"DefaultTenant\"},\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"identifier\":{\"key\":\"tenantName\",\"value\":\"Chocos05\"}},{\"domain\":{\"domainName\":\"alpine.com\"},\"entityTemplate\":{\"entityTemplateName\":\"DefaultTenant\"},\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"identifier\":{\"key\":\"tenantName\",\"value\":\"Chocos05\"}}]}";
	public final static String ATTACH_CHILDREN_SUMMARY = "Attach child entities to a parent entity";
	public final static String ATTACH_CHILDREN_SUCCESS_RESP = "{\"status\":\"SUCCESS\"}";

	public final static String ATTACH_PARENT_DESC = "This service is used to attach multiple parent entities to a child entity, sample request : "
	        + "{\"actor\":{\"domain\":{\"domainName\":\"alpine.com\"},\"entityTemplate\":{\"entityTemplateName\":\"DefaultTenant\"},\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"identifier\":{\"key\":\"tenantName\",\"value\":\"Chocos05\"}},\"subjects\":[{\"domain\":{\"domainName\":\"alpine.com\"},\"entityTemplate\":{\"entityTemplateName\":\"DefaultTenant\"},\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"identifier\":{\"key\":\"tenantName\",\"value\":\"Chocos05\"}},{\"domain\":{\"domainName\":\"alpine.com\"},\"entityTemplate\":{\"entityTemplateName\":\"DefaultTenant\"},\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"identifier\":{\"key\":\"tenantName\",\"value\":\"Chocos05\"}}]}";
	public final static String ATTACH_PARENT_SUMMARY = "Attach multiple parent entities to a child entity";
	public final static String ATTACH_PARENT__SUCCESS_RESP = "{\"status\":\"SUCCESS\"}";;

	public final static String HIERARCHY_PAYLOAD = "Hierarchy Payload";
	public final static String HIERARCHY_SEARCH_PAYLOAD = "Hierarchy Payload";

	public final static String TENANT_LINK_EXCEPTION = "Tenant cant be linked with any parent";
	public static final String GENERAL_FIELD_NOT_SPECIFIED = "{mandatory-field} not specified";
	public static final String GENERAL_FIELD_INVALID = "{field} is invalid";
	public static final String GENERAL_DATA_NOT_AVAILABLE = "Requested data is not available";
	public static final String ENTITIES_FROM_WRONG_HIERARCHY = "Entities are with wrong hierarchy";

	public final static String GET_CHILDREN_DESC = "This service is used to get the children under a parent, sample request : "
	        + "{\"parentIdentity\":{\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"domain\":{\"domainName\":\"alpine.com\"},\"entityTemplate\":{\"entityTemplateName\":\"DefaultTenant\"},\"identifier\":{\"key\":\"tenantName\",\"value\":\"cummins\"}},\"searchTemplateName\":\"DefaultTenant\",\"searchEntityType\":\"TENANT\"}";
	public final static String GET_CHILDREN_SUMMARY = "Get child entities";
	public final static String GET_CHILDREN__SUCCESS_RESP = "[{\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"domain\":{\"domainName\":\"cummins.alpine.com\"},\"entityStatus\":{\"statusKey\":0,\"statusName\":\"ACTIVE\"},\"entityTemplate\":{\"domain\":{\"domainName\":\"cummins.alpine.com\"},\"entityTemplateName\":\"DefaultTenant\",\"platformEntityType\":\"TENANT\"},\"dataprovider\":[],\"identifier\":{\"key\":\"tenantName\",\"value\":\"choco100\"}},{\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"domain\":{\"domainName\":\"cummins.alpine.com\"},\"entityStatus\":{\"statusKey\":0,\"statusName\":\"ACTIVE\"},\"entityTemplate\":{\"domain\":{\"domainName\":\"cummins.alpine.com\"},\"entityTemplateName\":\"DefaultTenant\",\"platformEntityType\":\"TENANT\"},\"dataprovider\":[],\"identifier\":{\"key\":\"tenantName\",\"value\":\"choco1002\"}}]";

	public final static String GET_CHILDREN_COUNT_DESC = "This service is used to get the number of children under a parent, sample request : "
	        + "{\"parentIdentity\":{\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"domain\":{\"domainName\":\"alpine.com\"},\"entityTemplate\":{\"entityTemplateName\":\"DefaultTenant\"},\"identifier\":{\"key\":\"tenantName\",\"value\":\"cummins\"}},\"searchTemplateName\":\"DefaultTenant\",\"searchEntityType\":\"TENANT\"}";
	public final static String GET_CHILDREN_COUNT_SUMMARY = "Get child count";
	public final static String GET_CHILDREN_COUNT_SUCCESS_RESP = "{\"count\": 2}";

	public final static String GET_STATUS_COUNT_DESC = "This service is used to get the number of children under a parent, sample request : "
	        + "{\"domain\":\"alpine.com\",\"searchTemplateName\":\"DefaultTenant\",\"searchEntityType\":\"TENANT\",\"statusName\":\"INACTIVE\"}";
	public final static String GET_STATUS_COUNT_SUMMARY = "Get count of nodes by status";
	public final static String GET_STATUS_COUNT_SUCCESS_RESP = "{\"count\": 2}";

	public final static String UPDATE_NODE_DEC = "This service is used to update a node, currenly only status. : {\"domain\":{\"domainName\":\"alpine.com\"},\"entityTemplate\":{\"entityTemplateName\":\"DefaultTenant\"},\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"identifier\":{\"key\":\"tenantName\",\"value\":\"Chocos05\"},\"entityStatus\":{\"statusName\":\"INACTIVE\"}}";
	public final static String UPDATE_NODE_SUMMARY = "Update nodes in hierarchy, currenly only status";
	public final static String UPDATE_NODE_RESP = "{\"domain\":{\"domainName\":\"alpine.com\"},\"entityTemplate\":{\"entityTemplateName\":\"DefaultTenant\"},\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"identifier\":{\"key\":\"tenantName\",\"value\":\"Chocos05\"},\"entityStatus\":{\"statusName\":\"INACTIVE\"}";

	public final static String GET_DISTRIBUTION_COUNT_DESC = "This service is used to get the entity distribution count, sample request : "
	        + "{\"parentIdentity\":{\"domain\":{\"domainName\":\"alpine.com\"},\"platformEntity\":{\"platformEntityType\":\"TENANT\"}},\"searchTemplateName\":\"Device\",\"statusName\":\"ACTIVE\"}";
	public final static String GET_DISTRIBUTION_COUNT_SUMMARY = "Get entity distribution count";
	public final static String GET_DISTRIBUTION_COUNT_SUCCESS_RESP = "[{\"count\":2,\"identifierValue\":\"cummins\"},{\"count\":3,\"identifierValue\":\"JLL\"}]";

	public final static String GET_DISTRIBUTION_DESC = "This service is used to get the entity distribution , sample request : "
	        + "{\"parentIdentity\":{\"domain\":{\"domainName\":\"alpine.com\"},\"platformEntity\":{\"platformEntityType\":\"TENANT\"}},\"searchTemplateName\":\"Device\",\"statusName\":\"ACTIVE\"}";
	public final static String GET_DISTRIBUTION_SUMMARY = "Get entity distribution";
	public final static String GET_DISTRIBUTION_SUCCESS_RESP = "[{\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"domain\":{\"domainName\":\"cummins.alpine.com\"},\"entityStatus\":{\"statusKey\":0,\"statusName\":\"ACTIVE\"},\"entityTemplate\":{\"domain\":{\"domainName\":\"cummins.alpine.com\"},\"entityTemplateName\":\"DefaultTenant\",\"platformEntityType\":\"TENANT\"},\"dataprovider\":[],\"identifier\":{\"key\":\"tenantName\",\"value\":\"choco100\"}},{\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"domain\":{\"domainName\":\"cummins.alpine.com\"},\"entityStatus\":{\"statusKey\":0,\"statusName\":\"ACTIVE\"},\"entityTemplate\":{\"domain\":{\"domainName\":\"cummins.alpine.com\"},\"entityTemplateName\":\"DefaultTenant\",\"platformEntityType\":\"TENANT\"},\"dataprovider\":[],\"identifier\":{\"key\":\"tenantName\",\"value\":\"choco1002\"}}]";

	public final static String GET_IMMEDIATE_CHILDREN_DESC = "This service is used to get the immediate children under a parent, sample request : "
	        + "{\"actor\":{\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"domain\":{\"domainName\":\"alpine.com\"},\"entityTemplate\":{\"entityTemplateName\":\"DefaultTenant\"},\"identifier\":{\"key\":\"tenantName\",\"value\":\"pacificcontrols\"}},\"searchTemplateName\":\"DefaultTenant\",\"searchEntityType\":\"TENANT\",\"statusName\":\"ACTIVE\"}";
	public final static String GET_IMMEDIATE_CHILDREN_SUMMARY = "Get immediate child entities";
	public final static String GET_IMMEDIATE_CHILDREN__SUCCESS_RESP = "[{\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"domain\":{\"domainName\":\"cummins.alpine.com\"},\"entityStatus\":{\"statusKey\":0,\"statusName\":\"ACTIVE\"},\"entityTemplate\":{\"domain\":{\"domainName\":\"cummins.alpine.com\"},\"entityTemplateName\":\"DefaultTenant\",\"platformEntityType\":\"TENANT\"},\"dataprovider\":[],\"identifier\":{\"key\":\"tenantName\",\"value\":\"choco100\"}},{\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"domain\":{\"domainName\":\"cummins.alpine.com\"},\"entityStatus\":{\"statusKey\":0,\"statusName\":\"ACTIVE\"},\"entityTemplate\":{\"domain\":{\"domainName\":\"cummins.alpine.com\"},\"entityTemplateName\":\"DefaultTenant\",\"platformEntityType\":\"TENANT\"},\"dataprovider\":[],\"identifier\":{\"key\":\"tenantName\",\"value\":\"choco1002\"}}]";

	public final static String GET_IMMEDIATE_PARENT_DESC = "This service is used to get the immediate parents of a child, sample request : "
	        + "{\"actor\":{\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"domain\":{\"domainName\":\"pacificcontrols.alpine.com\"},\"entityTemplate\":{\"entityTemplateName\":\"DefaultTenant\"},\"identifier\":{\"key\":\"tenantName\",\"value\":\"jll\"}},\"searchTemplateName\":\"DefaultTenant\",\"searchEntityType\":\"TENANT\",\"statusName\":\"ACTIVE\"}";
	public final static String GET_IMMEDIATE_PARENT_SUMMARY = "Get immediate parent entities";
	public final static String GET_IMMEDIATE_PARENT__SUCCESS_RESP = "[{\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"domain\":{\"domainName\":\"cummins.alpine.com\"},\"entityStatus\":{\"statusKey\":0,\"statusName\":\"ACTIVE\"},\"entityTemplate\":{\"domain\":{\"domainName\":\"cummins.alpine.com\"},\"entityTemplateName\":\"DefaultTenant\",\"platformEntityType\":\"TENANT\"},\"dataprovider\":[],\"identifier\":{\"key\":\"tenantName\",\"value\":\"choco100\"}},{\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"domain\":{\"domainName\":\"cummins.alpine.com\"},\"entityStatus\":{\"statusKey\":0,\"statusName\":\"ACTIVE\"},\"entityTemplate\":{\"domain\":{\"domainName\":\"cummins.alpine.com\"},\"entityTemplateName\":\"DefaultTenant\",\"platformEntityType\":\"TENANT\"},\"dataprovider\":[],\"identifier\":{\"key\":\"tenantName\",\"value\":\"choco1002\"}}]";
	public final static String GET_ASSIGNABLE_MARKER_DESC = "This service is used to get only the assignable markers : "
	        + "{\"actor\":{\"domain\":{\"domainName\":\"sanityclient002.pcs.alpine.com\"},\"identifier\":{\"key\":\"tenantName\",\"value\":\"sub001sanityclient002\"},\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"entityTemplate\":{\"entityTemplateName\":\"DefaultTenant\"}},\"searchTemplateName\":\"Point\",\"markerTemplateName\":\"Device\"}";
	public final static String GET_ASSIGNABLE_MARKER_SUMMARY = "Get Assignable Markers : ";
	public final static String GET_ASSIGNABLE_MARKER__SUCCESS_RESP = "[{\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"domain\":{\"domainName\":\"cummins.alpine.com\"},\"entityStatus\":{\"statusKey\":0,\"statusName\":\"ACTIVE\"},\"entityTemplate\":{\"domain\":{\"domainName\":\"cummins.alpine.com\"},\"entityTemplateName\":\"DefaultTenant\",\"platformEntityType\":\"TENANT\"},\"dataprovider\":[],\"identifier\":{\"key\":\"tenantName\",\"value\":\"choco100\"}},{\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"domain\":{\"domainName\":\"cummins.alpine.com\"},\"entityStatus\":{\"statusKey\":0,\"statusName\":\"ACTIVE\"},\"entityTemplate\":{\"domain\":{\"domainName\":\"cummins.alpine.com\"},\"entityTemplateName\":\"DefaultTenant\",\"platformEntityType\":\"TENANT\"},\"dataprovider\":[],\"identifier\":{\"key\":\"tenantName\",\"value\":\"choco1002\"}}]";
	public final static String GET_OWNED_MARKER_DESC = "This service is used to get all the markers owned by domain : "
	        + "{\"actor\":{\"domain\":{\"domainName\":\"sanityclient002.pcs.alpine.com\"},\"identifier\":{\"key\":\"tenantName\",\"value\":\"sub001sanityclient002\"},\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"entityTemplate\":{\"entityTemplateName\":\"DefaultPCSTemplate_TENANT\"}},\"searchTemplateName\":\"AvocadoPointTemplate\",\"markerTemplateName\":\"SaffronDeviceTemplate\"}";
	public final static String GET_OWNED_MARKER_SUMMARY = "Get All Owned Markers By Domain: ";
	public final static String GET_OWNED_MARKER__SUCCESS_RESP = "[{\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"domain\":{\"domainName\":\"cummins.alpine.com\"},\"entityStatus\":{\"statusKey\":0,\"statusName\":\"ACTIVE\"},\"entityTemplate\":{\"domain\":{\"domainName\":\"cummins.alpine.com\"},\"entityTemplateName\":\"DefaultPCSTemplate_TENANT\",\"platformEntityType\":\"TENANT\"},\"dataprovider\":[],\"identifier\":{\"key\":\"tenantName\",\"value\":\"choco100\"}},{\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"domain\":{\"domainName\":\"cummins.alpine.com\"},\"entityStatus\":{\"statusKey\":0,\"statusName\":\"ACTIVE\"},\"entityTemplate\":{\"domain\":{\"domainName\":\"cummins.alpine.com\"},\"entityTemplateName\":\"DefaultPCSTemplate_TENANT\",\"platformEntityType\":\"TENANT\"},\"dataprovider\":[],\"identifier\":{\"key\":\"tenantName\",\"value\":\"choco1002\"}}]";
	public final static String GET_TENANTS_WITHIN_RANGE_DESC = "This service is used to get all the tenants within specified range : "
	        + "{\"startEntity\":{\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"domain\":{\"domainName\":\"pcs.galaxy\"},\"entityTemplate\":{\"entityTemplateName\":\"DefaultTenant\"},\"identifier\":{\"key\":\"tenantName\",\"value\":\"srsinfotech\"}},\"endEntity\":{\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"domain\":{\"domainName\":\"srsclient.galaxy\"},\"entityTemplate\":{\"entityTemplateName\":\"DefaultTenant\"},\"identifier\":{\"key\":\"tenantName\",\"value\":\"srsclient01\"}}}";
	public final static String GET_TENANTS_WITHIN_RANGE_SUMMARY = "Get All Tenants Within Specified Range: ";
	public final static String GET_TENANTS_WITHIN_RANGE_SUCCESS_RESP = "[{\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"domain\":{\"domainName\":\"pcs.galaxy\"},\"entityStatus\":{\"statusKey\":0,\"statusName\":\"ACTIVE\"},\"entityTemplate\":{\"domain\":{\"domainName\":\"pcs.galaxy\"},\"entityTemplateName\":\"DefaultTenant\",\"platformEntityType\":\"TENANT\"},\"dataprovider\":[{\"key\":\"contactEmail\",\"value\":\"rajasathees@pacificcontrols.net\"},{\"key\":\"domain\",\"value\":\"srsinfotech.galaxy\"},{\"key\":\"firstName\",\"value\":\"Raja\"},{\"key\":\"lastName\",\"value\":\"S\"},{\"key\":\"tenantName\",\"value\":\"srsinfotech\"}],\"identifier\":{\"key\":\"tenantName\",\"value\":\"srsinfotech\"}}]";

	public final static String ATTACH_HIERARCHY_PAYLOAD = "Attach Hierarchy Payload";
	public final static String ATTACH_SUBJECTS_DESC = "This service is used to attach any subjects(entities or templates) to an actor"
	        + ", sample request to attach templates : "
	        + "{\"actorType\":\"ENTITY\",\"subjectType\":\"TEMPLATE\",\"actor\":{\"entity\":{\"platformEntity\":{\"platformEntityType\":\"MARKER\"},\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplate\":{\"entityTemplateName\":\"testTagType\"},\"identifier\":{\"key\":\"identifier\",\"value\":\"aff1920c-902d-4b9c-a213-0e0b5712b937\"}}},\"subject\":{\"templates\":[{\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"Asset\",\"platformEntityType\":\"MARKER\"}]}}"
	        + ", sample request to attach entities : "
	        + "{\"actorType\":\"ENTITY\",\"subjectType\":\"ENTITY\",\"actor\":{\"entity\":{\"platformEntity\":{\"platformEntityType\":\"MARKER\"},\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplate\":{\"entityTemplateName\":\"testTagType\"},\"identifier\":{\"key\":\"identifier\",\"value\":\"aff1920c-902d-4b9c-a213-0e0b5712b937\"}}},\"subject\":{\"entities\":[{\"platformEntity\":{\"platformEntityType\":\"MARKER\"},\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplate\":{\"entityTemplateName\":\"Asset\"},\"identifier\":{\"key\":\"identifier\",\"value\":\"ce470c87-10ca-4c13-a995-41df3cfce0df\"}},{\"platformEntity\":{\"platformEntityType\":\"MARKER\"},\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplate\":{\"entityTemplateName\":\"Asset\"},\"identifier\":{\"key\":\"identifier\",\"value\":\"88a0929a-e72c-4dde-97b1-aba1a7d4b745\"}}]}}";
	public final static String ATTACH_SUBJECTS_SUMMARY = "Attach subjects to an actor";
	public final static String ATTACH_SUBJECTS_SUCCESS_RESP = "{\"status\":\"SUCCESS\"}";

	public final static String ATTACH_ACTORS_DESC = "This service is used to attach actor entities to a subject, sample request : "
	        + "{\"actorType\":\"ENTITY\",\"subjectType\":\"ENTITY\",\"actor\":{\"entities\":[{\"platformEntity\":{\"platformEntityType\":\"MARKER\"},\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplate\":{\"entityTemplateName\":\"test01Tag\"},\"identifier\":{\"key\":\"identifier\",\"value\":\"4f988879-9bfc-4178-9d8d-ccd3d0f927aa\"}},{\"platformEntity\":{\"platformEntityType\":\"MARKER\"},\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplate\":{\"entityTemplateName\":\"BOOL\"},\"identifier\":{\"key\":\"identifier\",\"value\":\"ce470c87-10ca-4c13-a995-41df3cfce0df\"}},{\"platformEntity\":{\"platformEntityType\":\"MARKER\"},\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplate\":{\"entityTemplateName\":\"META\"},\"identifier\":{\"key\":\"identifier\",\"value\":\"88a0929a-e72c-4dde-97b1-aba1a7d4b745\"}}]},\"subject\":{\"entity\":{\"platformEntity\":{\"platformEntityType\":\"MARKER\"},\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplate\":{\"entityTemplateName\":\"Asset\"},\"identifier\":{\"key\":\"identifier\",\"value\":\"a9ddce9c-9e01-453c-8aaa-8a7f09468f0d\"}}}}";
	public final static String ATTACH_ACTORS_SUMMARY = "Attach actor entities to a subject";
	public final static String ATTACH_ACTORS_SUCCESS_RESP = "{\"status\":\"SUCCESS\"}";

	public final static String GET_ALL_ENTITIES_SUBJECTS_DESC = "This service is used to get all entities attached to Tag entity, sample request : "
	        + "{\"actorType\":\"ENTITY\",\"actor\":{\"entity\":{\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplate\":{\"entityTemplateName\":\"test01Tag\"},\"platformEntity\":{\"platformEntityType\":\"MARKER\"},\"identifier\":{\"key\":\"identifier\",\"value\":\"4f988879-9bfc-4178-9d8d-ccd3d0f927aa\"}}}}";
	public final static String GET_ALL_ENTITIES_SUBJECTS_SUMMARY = "Get all entities attached to Tag entity";
	public final static String GET_ALL_ENTITIES_SUBJECTS_RESP = "[{\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"domain\":{\"domainName\":\"demod.galaxy\"},\"entityStatus\":{\"statusName\":\"ACTIVE\"},\"entityTemplate\":{\"entityTemplateName\":\"DefaultTenant\"},\"dataprovider\":[{\"key\":\"contactEmail\",\"value\":\"twinkle@pacificcontrols.net\"},{\"key\":\"domain\",\"value\":\"subdemod.galaxy\"},{\"key\":\"firstName\",\"value\":\"subdemod\"},{\"key\":\"lastName\",\"value\":\"subdemod\"},{\"key\":\"tenantId\",\"value\":\"subdemod\"},{\"key\":\"tenantName\",\"value\":\"subdemod\"}],\"identifier\":{\"key\":\"tenantId\",\"value\":\"subdemod\"},\"tree\":{\"key\":\"tenantName\",\"value\":\"subdemod\"}}]";

	public final static String GET_ALL_TEMPLATES_SUBJECTS_DESC = "This service is used to get all templates attached to Tag entity, sample request : "
	        + "{\"actorType\":\"ENTITY\",\"actor\":{\"entity\":{\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplate\":{\"entityTemplateName\":\"test01Tag\"},\"platformEntity\":{\"platformEntityType\":\"MARKER\"},\"identifier\":{\"key\":\"identifier\",\"value\":\"4f988879-9bfc-4178-9d8d-ccd3d0f927aa\"}}}}";
	public final static String GET_ALL_TEMPLATES_SUBJECTS_SUMMARY = "Get all templates attached to Tag entity";
	public final static String GET_ALL_TEMPLATES_SUBJECTS_RESP = "[{\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"DefaultTenant\",\"platformEntityType\":\"TENANT\"},{\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"DefaultUser\",\"platformEntityType\":\"USER\"},{\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"Asset\",\"platformEntityType\":\"MARKER\"},{\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"Point\",\"platformEntityType\":\"MARKER\"}]";

	public final static String GET_IMMEDIATE_ROOTS_DESC = "This service is used to get immediate root tagEntities attached to a subject"
	        + ", sample request when subjec is a template : "
	        + "{\"domainName\":\"srsinfotech.galaxy\",\"actorType\":\"TEMPLATE\",\"actor\":{\"template\":{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"Asset\"}}}"
	        + ", sample request when subjec is an entity : "
	        + "{\"domainName\":\"srsinfotech.galaxy\",\"actorType\":\"ENTITY\",\"actor\":{\"entity\":{\"platformEntity\":{\"platformEntityType\":\"MARKER\"},\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplate\":{\"entityTemplateName\":\"Asset\"},\"identifier\":{\"key\":\"identifier\",\"value\":\"6cfa32bb-816b-4ae2-a789-fdb5b1e140be\"}}}}";
	public final static String GET_IMMEDIATE_ROOTS_SUMMARY = "Get immediate root tagEntities attached to a subject";
	public final static String GET_IMMEDIATE_ROOTS_RESP = "[{\"platformEntity\":{\"platformEntityType\":\"MARKER\"},\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityStatus\":{\"statusName\":\"ACTIVE\"},\"entityTemplate\":{\"entityTemplateName\":\"test01Tag\"},\"dataprovider\":[{\"key\":\"name\",\"value\":\"mech\"}],\"identifier\":{\"key\":\"identifier\",\"value\":\"4f988879-9bfc-4178-9d8d-ccd3d0f927aa\"}}]";

	public final static String GET_TEMPLATE_NAMES_OF_ATTACHED_ENTITIES_OF_DOMAIN_DESC = "This service is used to fetch template names of attached entities , sample request : "
	        + "{\"domain\":\"pcs.galaxy\",\"searchTemplateName\":\"Geotag\"}";
	public final static String GET_TEMPLATE_NAMES_OF_ATTACHED_ENTITIES_OF_DOMAIN_SUMMARY = "Fetch List of Entity Template Names of Attached Entities(Parent Entities) in a Domain";
	public final static String GET_TEMPLATE_NAMES_OF_ATTACHED_ENTITIES_OF_DOMAIN_SUCCESS_RESP = "[\"DefaultUser\",\"Asset\"]";

	public final static String TAG_ENITIES_BY_RANGE_DESC = "This is the service to be get tag entities by nodes range, sample requests"
	        + "1. when startNodeType:TEMPLATE and endNodeType:TEMPLATE : "
	        + "{\"startNodeType\":\"TEMPLATE\",\"endNodeType\":\"TEMPLATE\",\"startNode\":{\"template\":{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"Asset\"}},\"endNode\":{\"template\":{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"Point\"}},\"tagTypes\":[{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"META\"},{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"BOOL\"},{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"DEMOTAG\"},{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"XYZ\"},{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"test08Tag\"},{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"test09Tag\"}]}"
	        + " 2. when startNodeType:ENTITY and endNodeType:ENTITY : "
	        + "{\"startNodeType\":\"ENTITY\",\"endNodeType\":\"ENTITY\",\"startNode\":{\"entity\":{\"platformEntity\":{\"platformEntityType\":\"MARKER\"},\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplate\":{\"entityTemplateName\":\"Asset\"},\"identifier\":{\"key\":\"identifier\",\"value\":\"2ce054e3-e2f3-4daa-9fd2-78fc0489f03e\"}}},\"endNode\":{\"entity\":{\"platformEntity\":{\"platformEntityType\":\"MARKER\"},\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplate\":{\"entityTemplateName\":\"Point\"},\"identifier\":{\"key\":\"identifier\",\"value\":\"e48bc246-deb4-4b57-ad8b-cfcf46def759\"}}},\"tagTypes\":[{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"META\"},{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"BOOL\"},{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"DEMOTAG\"},{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"XYZ\"},{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"test08Tag\"},{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"test09Tag\"}]}"
	        + " 3. when startNodeType:TEMPLATE and endNodeType:ENTITY : "
	        + "{\"startNodeType\":\"TEMPLATE\",\"endNodeType\":\"ENTITY\",\"startNode\":{\"template\":{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"Asset\"}},\"endNode\":{\"entity\":{\"platformEntity\":{\"platformEntityType\":\"MARKER\"},\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplate\":{\"entityTemplateName\":\"Point\"},\"identifier\":{\"key\":\"identifier\",\"value\":\"e48bc246-deb4-4b57-ad8b-cfcf46def759\"}}},\"tagTypes\":[{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"META\"},{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"BOOL\"},{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"DEMOTAG\"},{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"XYZ\"},{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"test08Tag\"},{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"test09Tag\"}]}"
	        + " 4. when startNodeType:ENTITY and endNodeType:TEMPLATE : "
	        + "{\"startNodeType\":\"ENTITY\",\"endNodeType\":\"TEMPLATE\",\"startNode\":{\"entity\":{\"platformEntity\":{\"platformEntityType\":\"MARKER\"},\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplate\":{\"entityTemplateName\":\"Asset\"},\"identifier\":{\"key\":\"identifier\",\"value\":\"2ce054e3-e2f3-4daa-9fd2-78fc0489f03e\"}}},\"endNode\":{\"template\":{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"Point\"}},\"tagTypes\":[{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"META\"},{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"BOOL\"},{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"DEMOTAG\"},{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"XYZ\"},{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"test08Tag\"},{\"platformEntityType\":\"MARKER\",\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"test09Tag\"}]}";
	public final static String TAG_ENITIES_BY_RANGE_SUMMARY = "get tag entities by nodes range";
	public final static String TAG_ENITIES_BY_RANGE_RESP = "[{\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityStatus\":{\"statusName\":\"ACTIVE\"},\"entityTemplate\":{\"entityTemplateName\":\"test09Tag\"},\"dataprovider\":[{\"key\":\"name\",\"value\":\"mech\"}],\"identifier\":{\"key\":\"identifier\",\"value\":\"d6ee783c-8ffc-490d-9bbb-a9dce9167a6c\"}}]";

	public final static String SUBJECT__FILTERED_ENTITIES_DESC = "This is the service to be get entities which are attached to multiple startNodes, these entities can be filtered by template types, sample requests"
	        + " 1. When match : ANY is specified : {\"platformEntityTypes\":[\"MARKER\"],\"identifierKeys\":[\"identifier\"],\"identifierValues\":[\"4f988879-9bfc-4178-9d8d-ccd3d0f927aa\",\"d6ee783c-8ffc-490d-9bbb-a9dce9167a6c\"],\"domains\":[\"srsinfotech.galaxy\"],\"templateNames\":[\"test09Tag\",\"test01Tag\"],\"filter\":{\"templateNames\":[\"Asset\",\"Point\"]},\"match\":\"ANY\"}"
	        + " 2. When match : ALL is specified : {\"startNodes\":[{\"platformEntity\":{\"platformEntityType\":\"MARKER\"},\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityStatus\":{\"statusKey\":0,\"statusName\":\"ACTIVE\"},\"entityTemplate\":{\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityTemplateName\":\"DEMOTAG\",\"platformEntityType\":\"MARKER\"},\"identifier\":{\"key\":\"identifier\",\"value\":\"9fd14829-0f72-465b-a5af-0d4580623318\"}}],\"filter\":{\"templateNames\":[\"Asset\",\"Point\"]},\"match\":\"ALL\"}";
	public final static String SUBJECT__FILTERED_ENTITIES_SUMMARY = "get entities by multiple tags";
	public final static String SUBJECT__FILTERED_ENTITIES_RESP = "{\"Asset\":[{\"domain\":{\"domainName\":\"srsinfotech.galaxy\"},\"entityStatus\":{\"statusName\":\"ACTIVE\"},\"entityTemplate\":{\"entityTemplateName\":\"Asset\"},\"dataprovider\":[{\"key\":\"assetId\",\"value\":\"demoasset\"},{\"key\":\"assetName\",\"value\":\"demoasset\"},{\"key\":\"assetType\",\"value\":\"PUMP\"},{\"key\":\"description\"},{\"key\":\"identifier\",\"value\":\"44625b6d-19f8-444a-b506-88ad88696a5f\"},{\"key\":\"serialNumber\"}],\"identifier\":{\"key\":\"identifier\",\"value\":\"44625b6d-19f8-444a-b506-88ad88696a5f\"},\"tree\":{\"key\":\"assetId\",\"value\":\"demoasset\"}}],\"Point\":[]}";

	public final static String UPDATE_BATCH_STATUS_NODE_DEC = "This service is used to update the status of a list of nodes. : {\"domain\":{\"domainName\":\"alpine.com\"},\"entityTemplate\":{\"entityTemplateName\":\"DefaultTenant\"},\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"identifier\":{\"key\":\"tenantName\",\"value\":\"Chocos05\"},\"entityStatus\":{\"statusName\":\"INACTIVE\"}}";
	public final static String UPDATE_BATCH_STATUS_SUMMARY = "Update the status of nodes in hierarchy";
	public final static String UPDATE_BATCH_STATUS_RESP = "[{\"reference\":\"84fda99e-ecda-43df-a9cb-3c9817189198\",\"status\":\"SUCCESS\"},{\"reference\":\"cf02dad8-fa6a-42ba-8f8a-4150c5dccd55\",\"status\":\"FAILURE\",\"remarks\":\"Entity node is Invalid\"}]";

	public final static String ATTACH_MARKERS_MULTIPLE_PARENTS_DESC = "This service is used to attach multiple parent entities to multiple marker entities, sample request : "
	        + "{\"actor\":{\"domain\":{\"domainName\":\"alpine.com\"},\"entityTemplate\":{\"entityTemplateName\":\"DefaultTenant\"},\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"identifier\":{\"key\":\"tenantName\",\"value\":\"Chocos05\"}},\"subjects\":[{\"domain\":{\"domainName\":\"alpine.com\"},\"entityTemplate\":{\"entityTemplateName\":\"DefaultTenant\"},\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"identifier\":{\"key\":\"tenantName\",\"value\":\"Chocos05\"}},{\"domain\":{\"domainName\":\"alpine.com\"},\"entityTemplate\":{\"entityTemplateName\":\"DefaultTenant\"},\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"identifier\":{\"key\":\"tenantName\",\"value\":\"Chocos05\"}}]}";
	public final static String ATTACH_MARKERS_MULTIPLE_PARENTS_SUMMARY = "Attach multiple marker parent entities to multiple marker entities";
	public final static String ATTACH_MARKERS_MULTIPLE_PARENTS_SUCCESS_RESP = "{\"status\":\"SUCCESS\"}";

	public final static String GET_MARKERS_WITHIN_TENANTS_DESC = "This service is used to get markers between the specified tenants : "
	        + "{\"startEntity\":{\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"domain\":{\"domainName\":\"pcs.galaxy\"},\"entityTemplate\":{\"entityTemplateName\":\"DefaultTenant\"},\"identifier\":{\"key\":\"tenantId\",\"value\":\"jll\"}},\"endEntity\":{\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"domain\":{\"domainName\":\"alpine.galaxy\"},\"entityTemplate\":{\"entityTemplateName\":\"DefaultTenant\"},\"identifier\":{\"key\":\"tenantId\",\"value\":\"pcs\"}},\"searchTemplateName\":\"ServiceTags\"}";
	public final static String GET_MARKERS_WITHIN_TENANTS_SUMMARY = "Get All markers within tenants ";
	public final static String GET_MARKERS_WITHIN_TENANTS_SUCCESS_RESP = "[{\"platformEntity\":{\"platformEntityType\":\"MARKER\"},\"domain\":{\"domainName\":\"pcs.galaxy\"},\"entityStatus\":{\"statusName\":\"ACTIVE\"},\"entityTemplate\":{\"entityTemplateName\":\"ServiceTags\"},\"dataprovider\":[{\"key\":\"identifier\",\"value\":\"9cda00de-5414-4702-a80e-57b64caa8e50\"},{\"key\":\"name\",\"value\":\"Maintenance\"}],\"identifier\":{\"key\":\"identifier\",\"value\":\"9cda00de-5414-4702-a80e-57b64caa8e50\"},\"tree\":{\"key\":\"identifier\",\"value\":\"9cda00de-5414-4702-a80e-57b64caa8e50\"}},{\"platformEntity\":{\"platformEntityType\":\"MARKER\"},\"domain\":{\"domainName\":\"pcs.galaxy\"},\"entityStatus\":{\"statusName\":\"ACTIVE\"},\"entityTemplate\":{\"entityTemplateName\":\"ServiceTags\"},\"dataprovider\":[{\"key\":\"identifier\",\"value\":\"718c89bf-c411-4c0e-bd78-812a6b5deea1\"},{\"key\":\"name\",\"value\":\"Inspection\"}],\"identifier\":{\"key\":\"identifier\",\"value\":\"718c89bf-c411-4c0e-bd78-812a6b5deea1\"},\"tree\":{\"key\":\"identifier\",\"value\":\"718c89bf-c411-4c0e-bd78-812a6b5deea1\"}},{\"platformEntity\":{\"platformEntityType\":\"MARKER\"},\"domain\":{\"domainName\":\"pcs.galaxy\"},\"entityStatus\":{\"statusName\":\"ACTIVE\"},\"entityTemplate\":{\"entityTemplateName\":\"ServiceTags\"},\"dataprovider\":[{\"key\":\"identifier\",\"value\":\"82f9bccf-6c1d-46f7-a667-70af0f4dc4f5\"},{\"key\":\"name\",\"value\":\"Repair\"}],\"identifier\":{\"key\":\"identifier\",\"value\":\"82f9bccf-6c1d-46f7-a667-70af0f4dc4f5\"},\"tree\":{\"key\":\"identifier\",\"value\":\"82f9bccf-6c1d-46f7-a667-70af0f4dc4f5\"}}]";

	public final static String GET_TAGGED_ENTITIES_COUNT_DESC = "This service is used to get tagged entities count: "
	        + "{\"tagType\":\"FACILITY_TYPE\",\"domainName\":\"cisco.galaxy\",\"endEntityTemplate\":\"METER\",\"intermediateTemplates\":[\"Asset\",\"Device\"]}";
	public final static String GET_TAGGED_ENTITIES_COUNT_SUMMARY = "Get tagged entities count ";
	public final static String GET_TAGGED_ENTITIES_COUNT_SUCCESS_RESP = "[{\"tag\":\"Facility1\",\"count\":2},{\"tag\":\"Facility2\",\"count\":10}]";

}
