package com.pcs.avocado.constans;

/**
 * @description Responsible for holding the constants related to Swagger Api
 *              documentation
 * @author PCSEG199 (Javid Ahammed)
 * @date January 2016
 * @since avocado-1.0.0
 */
public interface DeviceResourceConstants {

	public static final String INSERT_DEVICE_SUMMARY = "Create a device";
	public static final String INSERT_DEVICE_DESC = "This service is used to create a new device into the application,sample request : {\"sourceId\": \"SourceId_From_Avocado_058\",\"make\": \"Teltonika\",\"deviceType\": \"Telematics\",\"model\": \"FMS\",\"protocol\": \"FM5300\",\"version\": \"1.0.0\",\"nwProtocol\": \"TCP\",\"configuration\": \"Teltonika_191215\",\"tags\": \"tag1,tag2\",\"isPublish\": \"true\",\"dsName\": \"Datacenter58\",\"deviceIp\": \"10.234.31.189\",\"devicePort\": \"795\",\"wbPort\": \"898\",\"allocated\": \"true\",\"status\": \"true\",\"deviceName\": \"device_01\"}";

	public static final String UPDATE_DEVICE_SUMMARY = "Update a device";
	public static final String UPDATE_DEVICE_DESC = "This service is used to update an existing device,sample request : {\"identifier\":\"18318bc1-aac4-4127-89e1-196d7ab2d620\",\"make\": \"Teltonika\",\"deviceType\": \"Telematics\",\"model\": \"FMS\",\"protocol\": \"FM5300\",\"version\": \"1.0.0\",\"nwProtocol\": \"TCP\",\"tags\": \"tag1,tag2\",\"isPublish\": \"false\",\"deviceIp\": \"10.234.31.189\",\"devicePort\": \"795\",\"wbPort\": \"898\",\"allocated\": \"false\",\"status\": \"true\"}";

	public static final String GET_DEVICE_DETAILS_SUMMARY = "Get details of the device";
	public static final String GET_DEVICE_DETAILS_DESC = "This is the service to be used to fetch the detail of the device";
	public static final String GET_DEVICE_DETAILS_SUCCESS_RESP = "{\"platformEntity\": {\"platformEntityType\": \"MARKER\"},\"domain\": {\"domainName\": \"pcs.alpine.com\"},\"entityStatus\": {\"statusKey\": 0,\"statusName\": \"ACTIVE\"},\"entityTemplate\": {\"domain\": {\"domainName\": \"pcs.alpine.com\"},\"entityTemplateName\": \"Device\",\"platformEntityType\": \"MARKER\"},\"dataprovider\": [{\"key\": \"datasourceName\",\"value\": \"Datacenter57\"},{\"key\": \"deviceType\",\"value\": \"Telematics\"},{\"key\": \"entityName\",\"value\": \"SourceId_From_Avocado_057\"},{\"key\": \"make\",\"value\": \"Teltonika\"},{\"key\": \"model\",\"value\": \"FMS\"},{\"key\": \"networkProtocol\",\"value\": \"TCP\"},{\"key\": \"protocol\",\"value\": \"FM5300\"},{\"key\": \"publish\",\"value\": \"true\"},{\"key\": \"tags\",\"value\": \"tag1,tag2\"},{\"key\": \"version\",\"value\": \"1.0.0\"}],\"identifier\": {\"key\": \"identifier\",\"value\": \"0b916793-c445-4376-aa5d-037e6f1188bb\"}}";

	public static final String CLAIM_DEVICE_SUMMARY = "Claim an unclaimed device";
	public static final String CLAIM_DEVICE_DESC = "This service is used to claim a device ,sample request : {\"make\": \"Teltonika\",\"deviceType\": \"Telematics\",\"model\": \"FMS\",\"protocol\": \"FM5300\",\"version\": \"1.0.0\",\"nwProtocol\": \"TCP\",\"tags\": \"tag1,tag2\",\"isPublish\": \"false\",\"deviceIp\": \"10.234.31.189\",\"devicePort\": \"795\",\"wbPort\": \"898\",\"allocated\": \"false\",\"status\": \"true\"}";

	public static final String CLAIM_DEVICES_SUMMARY = "Claim multiple unclaimed devices and assign to a client";
	public static final String CLAIM_DEVICES_DESC = "This service is used to claim multiple unclaimed devices and assign to a client ,sample request : {\"client\":{\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"domain\":{\"domainName\":\"cummins.galaxy\"},\"entityTemplate\":{\"entityTemplateName\":\"DefaultTenant\"},\"identifier\":{\"key\":\"tenantId\",\"value\":\"otr\"}},\"devices\":[{\"make\":\"G2021\",\"deviceType\":\"Edge Device\",\"model\":\"EDCP\",\"protocol\":\"EDCP\",\"version\":\"0.9.4\",\"nwProtocol\":\"TCP\",\"tags\":\"\",\"isPublish\":\"true\",\"allocated\":\"true\",\"status\":true,\"sourceId\":\"45898865498012\",\"deviceName\":\"45898865498012\"}]}";

	public static final String ASSIGN_DEVICES_SUMMARY = "Assign devices to tenant";
	public static final String ASSIGN_DEVICES_DESC = "This service is used to claim a device ,sample request : {\"actor\":{\"domain\":{\"domainName\":\"chocos.galaxy\"},\"identifier\":{\"key\":\"tenantId\",\"value\":\"chocos\"}},\"subjects\":[{\"domain\":{\"domainName\":\"pcs.galaxy\"},\"identifier\":{\"key\":\"identifier\",\"value\":\"4be1f23f-4574-44e4-ae69-cb27449c27e4\"}}]}";

	public static final String ASSIGN_BULK_DEVICES_SUMMARY = "Assign bulk devices to multiple tenants";
	public static final String ASSIGN_BULK_DEVICES_DESC = "This service is used to assign bulk devices to multiple tenants,sample request : {\r\n \"clientDevices\": [\r\n {\r\n \"devices\": [\r\n {\r\n \"platformEntity\": {\r\n \"platformEntityType\": \"MARKER\"\r\n },\r\n \"domain\": {\r\n \"domainName\": \"pcs.galaxy\"\r\n },\r\n \"entityTemplate\": {\r\n \"entityTemplateName\": \"Device\"\r\n },\r\n \"identifier\": {\r\n \"key\": \"identifier\",\r\n \"value\": \"1245-12124151-121511-21511\"\r\n }\r\n },\r\n {\r\n \"platformEntity\": {\r\n \"platformEntityType\": \"MARKER\"\r\n },\r\n \"domain\": {\r\n \"domainName\": \"pcs.galaxy\"\r\n },\r\n \"entityTemplate\": {\r\n \"entityTemplateName\": \"Device\"\r\n },\r\n \"identifier\": {\r\n \"key\": \"identifier\",\r\n \"value\": \"1245-12124151-121511-21333\"\r\n }\r\n }\r\n ],\r\n \"parent\": {\r\n \"platformEntity\": {\r\n \"platformEntityType\": \"TENANT\"\r\n },\r\n \"domain\": {\r\n \"domainName\": \"pcs.galaxy\"\r\n },\r\n \"entityTemplate\": {\r\n \"entityTemplateName\": \"DefaultTenant\"\r\n },\r\n \"identifier\": {\r\n \"key\": \"tenantId\",\r\n \"value\": \"cummins\"\r\n }\r\n }\r\n },\r\n {\r\n \"devices\": [\r\n {\r\n \"platformEntity\": {\r\n \"platformEntityType\": \"MARKER\"\r\n },\r\n \"domain\": {\r\n \"domainName\": \"pcs.galaxy\"\r\n },\r\n \"entityTemplate\": {\r\n \"entityTemplateName\": \"Device\"\r\n },\r\n \"identifier\": {\r\n \"key\": \"identifier\",\r\n \"value\": \"1245-12124151-121511-21527\"\r\n }\r\n }\r\n ],\r\n \"parent\": {\r\n \"platformEntity\": {\r\n \"platformEntityType\": \"TENANT\"\r\n },\r\n \"domain\": {\r\n \"domainName\": \"cummins.galaxy\"\r\n },\r\n \"entityTemplate\": {\r\n \"entityTemplateName\": \"DefaultTenant\"\r\n },\r\n \"identifier\": {\r\n \"key\": \"tenantId\",\r\n \"value\": \"otr\"\r\n }\r\n }\r\n }\r\n ],\r\n \"owner\": {\r\n \"platformEntity\": {\r\n \"platformEntityType\": \"TENANT\"\r\n },\r\n \"domain\": {\r\n \"domainName\": \"otr.galaxy\"\r\n },\r\n \"entityTemplate\": {\r\n \"entityTemplateName\": \"DefaultTenant\"\r\n },\r\n \"identifier\": {\r\n \"key\": \"tenantId\",\r\n \"value\": \"bigg\"\r\n }\r\n }\r\n}";

	public static final String LIST_DEVICES_SUMMARY = "List devices";
	public static final String LIST_DEVICES_DESC = "This service is used to list devices with an optional filter with tenant,sample request : {\"domain\":{\"domainName\":\"pcs.galaxy\"},\"identifier\":{\"key\":\"tenantId\",\"value\":\"cadbury\"}}";
	public static final String LIST_DEVICES_SUCCESS_RESP = "[{\"platformEntity\":{\"platformEntityType\": \"MARKER\"},\"domain\":{\"domainName\": \"pcs.alpine.com\"},\"entityStatus\":{\"statusKey\": 0,\"statusName\": \"ACTIVE\"},\"entityTemplate\": {\"domain\":{\"domainName\": \"pcs.alpine.com\"},\"entityTemplateName\": \"Device\",\"platformEntityType\": \"MARKER\"},\"dataprovider\": [{\"key\": \"datasourceName\",\"value\": \"Datacenter57\"},{\"key\": \"deviceType\",\"value\": \"Telematics\"},{\"key\": \"entityName\",\"value\": \"SourceId_From_Avocado_057\"},{\"key\": \"make\",\"value\": \"Teltonika\"},{\"key\": \"model\",\"value\": \"FMS\"},{\"key\": \"networkProtocol\",\"value\": \"TCP\"},{\"key\": \"protocol\",\"value\": \"FM5300\"},{\"key\": \"publish\",\"value\": \"true\"},{\"key\": \"tags\",\"value\": \"tag1,tag2\"},{\"key\": \"version\",\"value\": \"1.0.0\"}],\"identifier\": {\"key\": \"identifier\",\"value\": \"0b916793-c445-4376-aa5d-037e6f1188bb\"}},{\"platformEntity\":{\"platformEntityType\": \"MARKER\"},\"domain\":{\"domainName\": \"pcs.alpine.com\"},\"entityStatus\":{\"statusKey\": 0,\"statusName\": \"ACTIVE\"},\"entityTemplate\": {\"domain\":{\"domainName\": \"pcs.alpine.com\"},\"entityTemplateName\": \"Device\",\"platformEntityType\": \"MARKER\"},\"dataprovider\": [{\"key\": \"datasourceName\",\"value\": \"Teltonika Demo 1\"},{\"key\": \"deviceType\",\"value\": \"Telematics\"},{\"key\": \"entityName\",\"value\": \"8974516849563\"},{\"key\": \"make\",\"value\": \"Teltonika\"},{\"key\": \"model\",\"value\": \"FMS\"},{\"key\": \"networkProtocol\",\"value\": \"TCP\"},{\"key\": \"protocol\",\"value\": \"FM4200\"},{\"key\": \"publish\",\"value\": \"true\"},{\"key\": \"tags\",\"value\": \"\"},{\"key\": \"version\",\"value\": \"1.0.0\"}],\"identifier\": {\"key\": \"identifier\",\"value\": \"b4d142d4-60a1-4e26-a991-c8a2e65ba42a\"}}]";

	public static final String GET_DEVICE_LOC_DETAILS_SUMMARY = "Get device locations for a domain";
	public static final String GET_DEVICE_LOC_DETAILS_DESC = "This is the service to be used to fetch the device locations";
	public static final String GET_DEVICE_LOC_DETAILS_SUCCESS_RESP = "[{\"assetName\":\"bus001\",\"assetIdentifier\":{\"key\":\"identifier\",\"value\":\"8ea40f84-d87e-4a85-983f-f32e041ebee4\"},\"assetTemplate\":\"BUS\",\"location\":{\"latitude\":\"25.633995\",\"longitude\":\"55.49998\"},\"datasourceName\":\"895632102365475\",\"templateName\":\"Asset\"}]";

	public static final String LIST_LIVE_ALARMS_SUMMARY = "List of Live Alarms of all equipments";
	public static final String LIST_LIVE_ALARMS_DESC = "This service is used to fetch the list of Live alarms for all equipments";
	public static final String LIST_LIVE_ALARMS_RESP = "[{\"equipName\":\"gensetSourceId004\",\"equipIdentifier\":{\"key\":\"equipIdentifier\",\"value\":\"4a3495d9-498d-4aa0-b030-d2836f913bbe\"},\"equipTemplate\":\"Genset\",\"sourceId\":\"SourceId004\",\"alarmMessages\":[]},{\"equipName\":\"sayir_genset2001\",\"equipIdentifier\":{\"key\":\"equipIdentifier\",\"value\":\"614bbdbe-a6c7-44ab-ac53-044627ac630f\"},\"equipTemplate\":\"Genset\",\"sourceId\":\"sayirdevice2001\",\"alarmMessages\":[{\"alarmType\":\"OUT OF RANGE ALARM\",\"status\":\"true\",\"statusMessage\":\"LongitudeHighlimitAlarmActive\",\"data\":\"44.321266\",\"displayName\":\"Longitude\",\"time\":1439913707000},{\"alarmType\":\"OUT OF RANGE ALARM\",\"status\":\"true\",\"statusMessage\":\"LatitudeHighlimitAlarmActive\",\"data\":\"35.667896\",\"displayName\":\"Latitude\",\"time\":1439913688000}]},{\"equipName\":\"gensetSourceId006\",\"equipIdentifier\":{\"key\":\"equipIdentifier\",\"value\":\"cc0500ad-a37c-4245-b2ff-3eec29cece19\"},\"equipTemplate\":\"Genset\",\"sourceId\":\"SourceId006\",\"alarmMessages\":[]}]";

	public static final String LIST_ALARM_HISTORY_SUMMARY = "List of Alarms of all equipments for a given date range";
	public static final String LIST_ALARM_HISTORY_DESC = "This service is used to fetch the list of Live alarms for all equipments for a given date range";
	public static final String LIST_ALARM_HISTORY_RESP = "[{\"equipName\":\"gensetSourceId004\",\"equipIdentifier\":{\"key\":\"equipIdentifier\",\"value\":\"4a3495d9-498d-4aa0-b030-d2836f913bbe\"},\"equipTemplate\":\"Genset\",\"sourceId\":\"SourceId004\",\"alarmMessages\":[]},{\"equipName\":\"sayir_genset2001\",\"equipIdentifier\":{\"key\":\"equipIdentifier\",\"value\":\"614bbdbe-a6c7-44ab-ac53-044627ac630f\"},\"equipTemplate\":\"Genset\",\"sourceId\":\"sayirdevice2001\",\"alarmMessages\":[{\"alarmType\":\"OUT OF RANGE ALARM\",\"status\":\"true\",\"statusMessage\":\"LongitudeHighlimitAlarmActive\",\"data\":\"44.321266\",\"displayName\":\"Longitude\",\"time\":1439913707000},{\"alarmType\":\"OUT OF RANGE ALARM\",\"status\":\"false\",\"statusMessage\":\"LongitudeNormal\",\"data\":\"25.727715\",\"displayName\":\"Longitude\",\"time\":1439913646000},{\"alarmType\":\"OUT OF RANGE ALARM\",\"status\":\"true\",\"statusMessage\":\"LongitudeHighlimitAlarmActive\",\"data\":\"42.193974\",\"displayName\":\"Longitude\",\"time\":1439913627000}]}]";

	public final static String GET_OWNED_DEVICES_DESC = "This service is used to get all the markers owned by domain : "
	        + "{\"domain\":{\"domainName\":\"pcs.galaxy\"},\"entityTemplate\":{\"entityTemplateName\":\"DefaultTenant\"},\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"identifier\":{\"key\":\"tenantName\",\"value\":\"fanta\"}}";
	public final static String GET_OWNED_DEVICES_SUMMARY = "Get All Owned Markers By Domain: ";
	public final static String GET_OWNED_DEVICES__SUCCESS_RESP = "[{\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"domain\":{\"domainName\":\"cummins.alpine.com\"},\"entityStatus\":{\"statusKey\":0,\"statusName\":\"ACTIVE\"},\"entityTemplate\":{\"domain\":{\"domainName\":\"cummins.alpine.com\"},\"entityTemplateName\":\"DefaultPCSTemplate_TENANT\",\"platformEntityType\":\"TENANT\"},\"dataprovider\":[],\"identifier\":{\"key\":\"tenantName\",\"value\":\"choco100\"}},{\"platformEntity\":{\"platformEntityType\":\"TENANT\"},\"domain\":{\"domainName\":\"cummins.alpine.com\"},\"entityStatus\":{\"statusKey\":0,\"statusName\":\"ACTIVE\"},\"entityTemplate\":{\"domain\":{\"domainName\":\"cummins.alpine.com\"},\"entityTemplateName\":\"DefaultPCSTemplate_TENANT\",\"platformEntityType\":\"TENANT\"},\"dataprovider\":[],\"identifier\":{\"key\":\"tenantName\",\"value\":\"choco1002\"}}]";

	public final static String GET_DEVICES_BY_DS_DESC = "This service is used to get all devices by searching by the datasources : "
	        + "[\"259642460480401\"]\n";
	public final static String GET_DEVICES_BY_DS_SUMMARY = "Get devices by datasources";
	public final static String GET_DEVICES_BY_DS_SUCCESS_RESP = "[{\"platformEntity\":{\"platformEntityType\":\"MARKER\"},\"domain\":{\"domainName\":\"pcs.galaxy\"},\"entityTemplate\":{\"domain\":{\"domainName\":\"pcs.galaxy\"},\"entityTemplateName\":\"Device\",\"platformEntityType\":\"MARKER\"},\"identifier\":{\"key\":\"identifier\",\"value\":\"77534a94-3b5f-4813-ab97-3bf2a301ef02\"},\"returnFields\":[],\"dataprovider\":[{\"key\":\"datasourceName\",\"value\":\"259642460480401\"},{\"key\":\"deviceName\",\"value\":\"R115LLA0313\"},{\"key\":\"deviceType\",\"value\":\"Edge Device\"},{\"key\":\"entityName\",\"value\":\"259642460480401\"},{\"key\":\"latitude\",\"value\":\"39.32082\"},{\"key\":\"longitude\",\"value\":\"-78.07166\"},{\"key\":\"make\",\"value\":\"G2021\"},{\"key\":\"model\",\"value\":\"EDCP\"},{\"key\":\"networkProtocol\",\"value\":\"TCP\"},{\"key\":\"protocol\",\"value\":\"EDCP\"},{\"key\":\"publish\",\"value\":\"true\"},{\"key\":\"slot\"},{\"key\":\"tags\"},{\"key\":\"url\"},{\"key\":\"version\",\"value\":\"0.9.4\"}],\"entityStatus\":{\"statusKey\":0,\"statusName\":\"ACTIVE\"}}]";
}
