
package org.wso2.carbon.event.execution.manager.admin;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.wso2.carbon.event.execution.manager.admin.dto.configuration.xsd.TemplateConfigurationDTO;
import org.wso2.carbon.event.execution.manager.admin.dto.configuration.xsd.TemplateConfigurationInfoDTO;
import org.wso2.carbon.event.execution.manager.admin.dto.domain.xsd.TemplateDomainDTO;
import org.wso2.carbon.event.execution.manager.admin.dto.domain.xsd.TemplateDomainInfoDTO;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExecutionManagerAdminServicePortType", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org")
@XmlSeeAlso({
    org.wso2.carbon.event.execution.manager.admin.ObjectFactory.class,
    org.wso2.carbon.event.execution.manager.admin.dto.configuration.xsd.ObjectFactory.class,
    org.wso2.carbon.event.execution.manager.admin.dto.domain.xsd.ObjectFactory.class
})
public interface ExecutionManagerAdminServicePortType {


    /**
     * 
     * @param configuration
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(action = "urn:saveConfiguration")
    @WebResult(targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org")
    @RequestWrapper(localName = "saveConfiguration", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org", className = "org.wso2.carbon.event.execution.manager.admin.SaveConfiguration")
    @ResponseWrapper(localName = "saveConfigurationResponse", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org", className = "org.wso2.carbon.event.execution.manager.admin.SaveConfigurationResponse")
    public Boolean saveConfiguration(
        @WebParam(name = "configuration", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org")
        TemplateConfigurationDTO configuration);

    /**
     * 
     * @param domainName
     * @return
     *     returns org.wso2.carbon.event.execution.manager.admin.dto.domain.xsd.TemplateDomainDTO
     */
    @WebMethod(action = "urn:getDomain")
    @WebResult(targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org")
    @RequestWrapper(localName = "getDomain", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org", className = "org.wso2.carbon.event.execution.manager.admin.GetDomain")
    @ResponseWrapper(localName = "getDomainResponse", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org", className = "org.wso2.carbon.event.execution.manager.admin.GetDomainResponse")
    public TemplateDomainDTO getDomain(
        @WebParam(name = "domainName", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org")
        String domainName);

    /**
     * 
     * @param domainName
     * @return
     *     returns java.util.List<org.wso2.carbon.event.execution.manager.admin.dto.configuration.xsd.TemplateConfigurationDTO>
     */
    @WebMethod(action = "urn:getConfigurations")
    @WebResult(targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org")
    @RequestWrapper(localName = "getConfigurations", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org", className = "org.wso2.carbon.event.execution.manager.admin.GetConfigurations")
    @ResponseWrapper(localName = "getConfigurationsResponse", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org", className = "org.wso2.carbon.event.execution.manager.admin.GetConfigurationsResponse")
    public List<TemplateConfigurationDTO> getConfigurations(
        @WebParam(name = "domainName", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org")
        String domainName);

    /**
     * 
     * @param domainName
     * @return
     *     returns java.util.List<org.wso2.carbon.event.execution.manager.admin.dto.configuration.xsd.TemplateConfigurationInfoDTO>
     */
    @WebMethod(action = "urn:getConfigurationsInfo")
    @WebResult(targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org")
    @RequestWrapper(localName = "getConfigurationsInfo", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org", className = "org.wso2.carbon.event.execution.manager.admin.GetConfigurationsInfo")
    @ResponseWrapper(localName = "getConfigurationsInfoResponse", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org", className = "org.wso2.carbon.event.execution.manager.admin.GetConfigurationsInfoResponse")
    public List<TemplateConfigurationInfoDTO> getConfigurationsInfo(
        @WebParam(name = "domainName", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org")
        String domainName);

    /**
     * 
     * @param configName
     * @param domainName
     * @return
     *     returns org.wso2.carbon.event.execution.manager.admin.dto.configuration.xsd.TemplateConfigurationDTO
     */
    @WebMethod(action = "urn:getConfiguration")
    @WebResult(targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org")
    @RequestWrapper(localName = "getConfiguration", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org", className = "org.wso2.carbon.event.execution.manager.admin.GetConfiguration")
    @ResponseWrapper(localName = "getConfigurationResponse", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org", className = "org.wso2.carbon.event.execution.manager.admin.GetConfigurationResponse")
    public TemplateConfigurationDTO getConfiguration(
        @WebParam(name = "domainName", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org")
        String domainName,
        @WebParam(name = "configName", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org")
        String configName);

    /**
     * 
     * @return
     *     returns java.util.List<org.wso2.carbon.event.execution.manager.admin.dto.domain.xsd.TemplateDomainInfoDTO>
     */
    @WebMethod(action = "urn:getAllDomainsInfo")
    @WebResult(targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org")
    @RequestWrapper(localName = "getAllDomainsInfo", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org", className = "org.wso2.carbon.event.execution.manager.admin.GetAllDomainsInfo")
    @ResponseWrapper(localName = "getAllDomainsInfoResponse", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org", className = "org.wso2.carbon.event.execution.manager.admin.GetAllDomainsInfoResponse")
    public List<TemplateDomainInfoDTO> getAllDomainsInfo();

    /**
     * 
     * @return
     *     returns java.util.List<org.wso2.carbon.event.execution.manager.admin.dto.domain.xsd.TemplateDomainDTO>
     */
    @WebMethod(action = "urn:getAllDomains")
    @WebResult(targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org")
    @RequestWrapper(localName = "getAllDomains", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org", className = "org.wso2.carbon.event.execution.manager.admin.GetAllDomains")
    @ResponseWrapper(localName = "getAllDomainsResponse", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org", className = "org.wso2.carbon.event.execution.manager.admin.GetAllDomainsResponse")
    public List<TemplateDomainDTO> getAllDomains();

    /**
     * 
     * @param configName
     * @param domainName
     * @return
     *     returns org.wso2.carbon.event.execution.manager.admin.dto.configuration.xsd.TemplateConfigurationInfoDTO
     */
    @WebMethod(action = "urn:getConfigurationInfo")
    @WebResult(targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org")
    @RequestWrapper(localName = "getConfigurationInfo", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org", className = "org.wso2.carbon.event.execution.manager.admin.GetConfigurationInfo")
    @ResponseWrapper(localName = "getConfigurationInfoResponse", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org", className = "org.wso2.carbon.event.execution.manager.admin.GetConfigurationInfoResponse")
    public TemplateConfigurationInfoDTO getConfigurationInfo(
        @WebParam(name = "domainName", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org")
        String domainName,
        @WebParam(name = "configName", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org")
        String configName);

    /**
     * 
     * @param configName
     * @param domainName
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(action = "urn:deleteConfiguration")
    @WebResult(targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org")
    @RequestWrapper(localName = "deleteConfiguration", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org", className = "org.wso2.carbon.event.execution.manager.admin.DeleteConfiguration")
    @ResponseWrapper(localName = "deleteConfigurationResponse", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org", className = "org.wso2.carbon.event.execution.manager.admin.DeleteConfigurationResponse")
    public Boolean deleteConfiguration(
        @WebParam(name = "domainName", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org")
        String domainName,
        @WebParam(name = "configName", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org")
        String configName);

    /**
     * 
     * @param domainName
     * @return
     *     returns org.wso2.carbon.event.execution.manager.admin.dto.domain.xsd.TemplateDomainInfoDTO
     */
    @WebMethod(action = "urn:getDomainInfo")
    @WebResult(targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org")
    @RequestWrapper(localName = "getDomainInfo", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org", className = "org.wso2.carbon.event.execution.manager.admin.GetDomainInfo")
    @ResponseWrapper(localName = "getDomainInfoResponse", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org", className = "org.wso2.carbon.event.execution.manager.admin.GetDomainInfoResponse")
    public TemplateDomainInfoDTO getDomainInfo(
        @WebParam(name = "domainName", targetNamespace = "http://admin.manager.execution.event.carbon.wso2.org")
        String domainName);

}
