   registryHost : 192.168.4.9
   registryPort : 1099   
   registryName : distributor
   host : 192.168.4.6
   port : 8282
   scheme : http
   ccdresponseUrl : ccd1/1.0.0/receiveData
   apiMgrClientId : S18xVDuqIfe2lnAnBi2YcOWeTeoa
   apiMgrClientSecret : o7RIriH3_PAwzzws1DaqdVxcSfwa
   ccdUser : ccdadmin@ccd.galaxy
   ccdUserPwd : password
