package com.pcs.device.gateway.meitrack.command.types;

public enum CommandTypes {
	
	TRACK_ON_DEMAND("A10"),
	SET_HEARTBEAT_INTERVAL("A11"),
	TRACK_BY_TIME_INTERVAL("A12"),
	SET_HEAD_CHANGE_REPORT("A13"),
	TRACK_BY_DISTANCE("A14"),
	SET_GPRS("A21"),
	SET_DNS_SERVER("A22"),
	SET_SECONDARY_DNS_SERVER("A23"),
	GET_AUTHORIZED_PHONENUMBERS("A70"),
	AUTHORIZE_FUNCTION_PHONENUMBER("A71"),
	VOICE_MONITORING("A72"),
	SET_SLEEP_MODE("A73"),
	DELETE_BUFFER_QUEUE("AFF"),
	GET_AUTHORIZED_PHONENUMBER_SMS_EVENT_FLAG("B00"),
	AUTHORIZE_PHONENUMBER_SMS_EVENT_FLAG("B01"),
	SET_SMS_EVENT_FLAG_TO_PHONENUMBER("B02"),
	DELETE_SMS_EVENT_FLAG_TO_PHONENUMBER("B03"),
	SET_GEOFENCE_ALARM("B05"),
	DELETE_GEOFENCE_WAYPOINT("B06"),
	SET_SPEEDING_ALARM("B07"),
	SET_TOW_ALARM("B08"),
	SET_TREMBLE_SENSITIVITY("B09"),
	SET_TREMBLE_SENSITIVITY_MVT600("B20"),
	SET_EXTENDED_FUNCTIONS("B31"),
	SET_GPS_SLEEP_MODE("B32"),
	SET_POWER_DOWN_MODE("B33"),
	SET_LOG_INTERVAL("B34"),
	TIME_ZONE_SETTING_SMS("B35"),
	TIME_ZONE_SETTING_GPRS("B36"),
	SET_SMS_HEADER_FOR_EVENT("B91"),
	SET_EVENT_FLAG_FOR_GPRS("B92"),
	GET_EVENT_FLAG_FOR_GPRS("B93"),
	SET_EVENT_FLAG_FOR_PICTURE("B96"),
	GET_EVENT_FLAG_FOR_PICTURE("B97"),
	OUTPUT_CONTORL("C01"),
	PROTOCOL_CONTROL("CO3"),
	GPRS_MESSAGE_DISPLAY("C10"),
	TAKE_PICTURE("D00"),
	GET_PICTURE_FILENAME("D01"),
	DELETE_PICTURE("D02"),
	TAKE_ONE_PICTURE("D03"),
	GET_FIRMWARE_VERSION_SN("E91"),
	REBOOT_GSM_MODULE("F01"),
	REBOOT_GPS_MODULE("F02"),
	CLEAR_JOURNEY_AND_RUNNING_TIME("F06"),
	CLEAR_SMS_GPRS_BUFFER("F09"),
	INITIALIZATION("F11");

	
	private String command;
	
	public String getCommand() {
		return command;
	}

	public void setCommand(String command) {
		this.command = command;
	}

	private CommandTypes(String command){
		this.command = command;
	}
}
